/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.security;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpMethod;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.core.annotation.Order;

@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
@EnableWebSecurity
@ComponentScan("co.rtapps.security")
@Order(99999)
public class ServiceSecurityConfig extends WebSecurityConfigurerAdapter {
	@Autowired
	private UserDetailsService userDetailsService;

	@Bean
	public BCryptPasswordEncoder bCryptPasswordEncoder() {
		return new BCryptPasswordEncoder();
	}

	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http.httpBasic().and().authorizeRequests()
			.antMatchers("/user/**").hasAuthority("ROLE_ADMIN")
			.antMatchers(HttpMethod.POST,"/user/add").hasAnyAuthority("ROLE_ADMIN")
			.antMatchers(HttpMethod.DELETE,"/user/**").hasAnyAuthority("ROLE_ADMIN")
			.antMatchers("/**").hasAnyAuthority("ROLE_USER","ROLE_ADMIN")
/*
* Generated for each one of the end points
* Uncomment for more control
*/
/*

                .antMatchers(HttpMethod.GET, "/acceptableitemss/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/acceptableitemss/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/acceptableitemss/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/acceptableitemss/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/businessunits/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/businessunits/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/businessunits/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/businessunits/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/facilitys/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/facilitys/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/facilitys/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/facilitys/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/facilitycontactinformations/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/facilitycontactinformations/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/facilitycontactinformations/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/facilitycontactinformations/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/genesyschats/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/genesyschats/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/genesyschats/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/genesyschats/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/holidayschedules/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/holidayschedules/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/holidayschedules/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/holidayschedules/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/lclserviceareas/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/lclserviceareas/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/lclserviceareas/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/lclserviceareas/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/lclserviceareapostalcodes/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/lclserviceareapostalcodes/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/lclserviceareapostalcodes/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/lclserviceareapostalcodes/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/marketareatables/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/marketareatables/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/marketareatables/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/marketareatables/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/operatingschedules/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/operatingschedules/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/operatingschedules/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/operatingschedules/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/recordtypes/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/recordtypes/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/recordtypes/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/recordtypes/**").hasAnyAuthority("ROLE_USER")
*/
/*
* Generated for each one of the end points
* Uncomment for more control.
*/
/*

                .antMatchers(HttpMethod.GET, "/api/v1/acceptableitems/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/acceptableitems/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/acceptableitems/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/acceptableitems/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/businessunit/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/businessunit/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/businessunit/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/businessunit/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/facility/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/facility/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/facility/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/facility/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/facilitycontactinformation/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/facilitycontactinformation/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/facilitycontactinformation/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/facilitycontactinformation/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/genesyschat/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/genesyschat/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/genesyschat/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/genesyschat/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/holidayschedule/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/holidayschedule/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/holidayschedule/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/holidayschedule/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/lclservicearea/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/lclservicearea/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/lclservicearea/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/lclservicearea/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/lclserviceareapostalcode/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/lclserviceareapostalcode/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/lclserviceareapostalcode/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/lclserviceareapostalcode/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/marketareatable/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/marketareatable/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/marketareatable/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/marketareatable/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/operatingschedule/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/operatingschedule/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/operatingschedule/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/operatingschedule/**").hasAnyAuthority("ROLE_USER")

                .antMatchers(HttpMethod.GET, "/api/v1/recordtype/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.POST, "/api/v1/recordtype/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.PUT, "/api/v1/recordtype/**").hasAnyAuthority("ROLE_USER")
                .antMatchers(HttpMethod.DELETE, "/api/v1/recordtype/**").hasAnyAuthority("ROLE_USER")
*/
			.anyRequest().authenticated().and().csrf().disable();
	}

	@Autowired
	public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception {
		auth.userDetailsService(userDetailsService).passwordEncoder(bCryptPasswordEncoder());
	}

}
