/*
 * Created on 2017-09-12 ( Time 13:14:26 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class AcceptableItemsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public AcceptableItemsNotFoundException(Integer id) {
		super("AcceptableItems not found with id: " + id.toString());
	}

	public AcceptableItemsNotFoundException(String acceptableitems) {
		super("AcceptableItems " + acceptableitems + " not found!");
	}
}
