/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class BusinessUnitNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public BusinessUnitNotFoundException(Integer id) {
		super("BusinessUnit not found with id: " + id.toString());
	}

	public BusinessUnitNotFoundException(String businessunit) {
		super("BusinessUnit " + businessunit + " not found!");
	}
}
