/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class FacilityNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public FacilityNotFoundException(Integer id) {
		super("Facility not found with id: " + id.toString());
	}

	public FacilityNotFoundException(String facility) {
		super("Facility " + facility + " not found!");
	}
}
