/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class FacilityContactInformationNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public FacilityContactInformationNotFoundException(Integer id) {
		super("FacilityContactInformation not found with id: " + id.toString());
	}

	public FacilityContactInformationNotFoundException(String facilitycontactinformation) {
		super("FacilityContactInformation " + facilitycontactinformation + " not found!");
	}
}
