/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class GenesysChatNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public GenesysChatNotFoundException(Integer id) {
		super("GenesysChat not found with id: " + id.toString());
	}

	public GenesysChatNotFoundException(String genesyschat) {
		super("GenesysChat " + genesyschat + " not found!");
	}
}
