/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class HolidayScheduleNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public HolidayScheduleNotFoundException(Integer id) {
		super("HolidaySchedule not found with id: " + id.toString());
	}

	public HolidayScheduleNotFoundException(String holidayschedule) {
		super("HolidaySchedule " + holidayschedule + " not found!");
	}
}
