/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class LclServiceAreaNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public LclServiceAreaNotFoundException(Integer id) {
		super("LclServiceArea not found with id: " + id.toString());
	}

	public LclServiceAreaNotFoundException(String lclservicearea) {
		super("LclServiceArea " + lclservicearea + " not found!");
	}
}
