/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class MarketAreaTableNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public MarketAreaTableNotFoundException(Integer id) {
		super("MarketAreaTable not found with id: " + id.toString());
	}

	public MarketAreaTableNotFoundException(String marketareatable) {
		super("MarketAreaTable " + marketareatable + " not found!");
	}
}
