/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class OperatingScheduleNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public OperatingScheduleNotFoundException(Integer id) {
		super("OperatingSchedule not found with id: " + id.toString());
	}

	public OperatingScheduleNotFoundException(String operatingschedule) {
		super("OperatingSchedule " + operatingschedule + " not found!");
	}
}
