/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.exceptions;

public class RecordtypeNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public RecordtypeNotFoundException(Integer id) {
		super("Recordtype not found with id: " + id.toString());
	}

	public RecordtypeNotFoundException(String recordtype) {
		super("Recordtype " + recordtype + " not found!");
	}
}
