/*
 * Created on 2017-09-12 ( Time 13:14:26 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wm.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "acceptable_items__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="acceptable_items__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="AcceptableItems.countAll", query="SELECT COUNT(x) FROM AcceptableItems x" )
} )
public class AcceptableItems implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="name", length=80)
    private String     name         ;


    @Column(name="item_name__c", length=50)
    private String     itemNameCustom ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Column(name="createdbyid", length=18)
    private String     createdbyid  ;


    @Column(name="acceptable__c", length=255)
    private String     acceptableCustom ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;


    @Column(name="item_note__c", length=100)
    private String     itemNoteCustom ;


    @Column(name="facility__c", length=18)
    private String     facilityCustom ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="acceptable_item__c", length=18)
    private String     acceptableItemCustom ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Column(name="hazardous_waste__c", length=255)
    private String     hazardousWasteCustom ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AcceptableItems()
    {
		super();
    }

    public AcceptableItems update(AcceptableItems a) {
		this.id = a.id;
        this.name = a.name;
        this.itemNameCustom = a.itemNameCustom;
        this.isdeleted = a.isdeleted;
        this.createdbyid = a.createdbyid;
        this.acceptableCustom = a.acceptableCustom;
        this.hcLastop = a.hcLastop;
        this.hcErr = a.hcErr;
        this.itemNoteCustom = a.itemNoteCustom;
        this.facilityCustom = a.facilityCustom;
        this.systemmodstamp = a.systemmodstamp;
        this.acceptableItemCustom = a.acceptableItemCustom;
        this.sfid = a.sfid;
        this.createddate = a.createddate;
        this.hazardousWasteCustom = a.hazardousWasteCustom;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : item_name__c ( varchar ) 
    public void setItemNameCustom( String itemNameCustom )
    {
        this.itemNameCustom = itemNameCustom;
    }
    public String getItemNameCustom()
    {
        return this.itemNameCustom;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : createdbyid ( varchar ) 
    public void setCreatedbyid( String createdbyid )
    {
        this.createdbyid = createdbyid;
    }
    public String getCreatedbyid()
    {
        return this.createdbyid;
    }

    //--- DATABASE MAPPING : acceptable__c ( varchar ) 
    public void setAcceptableCustom( String acceptableCustom )
    {
        this.acceptableCustom = acceptableCustom;
    }
    public String getAcceptableCustom()
    {
        return this.acceptableCustom;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : item_note__c ( varchar ) 
    public void setItemNoteCustom( String itemNoteCustom )
    {
        this.itemNoteCustom = itemNoteCustom;
    }
    public String getItemNoteCustom()
    {
        return this.itemNoteCustom;
    }

    //--- DATABASE MAPPING : facility__c ( varchar ) 
    public void setFacilityCustom( String facilityCustom )
    {
        this.facilityCustom = facilityCustom;
    }
    public String getFacilityCustom()
    {
        return this.facilityCustom;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : acceptable_item__c ( varchar ) 
    public void setAcceptableItemCustom( String acceptableItemCustom )
    {
        this.acceptableItemCustom = acceptableItemCustom;
    }
    public String getAcceptableItemCustom()
    {
        return this.acceptableItemCustom;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : hazardous_waste__c ( varchar ) 
    public void setHazardousWasteCustom( String hazardousWasteCustom )
    {
        this.hazardousWasteCustom = hazardousWasteCustom;
    }
    public String getHazardousWasteCustom()
    {
        return this.hazardousWasteCustom;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(itemNameCustom);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(createdbyid);
        sb.append("|");
        sb.append(acceptableCustom);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(itemNoteCustom);
        sb.append("|");
        sb.append(facilityCustom);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(acceptableItemCustom);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(hazardousWasteCustom);
        return sb.toString(); 
    } 

}