/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wm.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "business_unit__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="business_unit__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="BusinessUnit.countAll", query="SELECT COUNT(x) FROM BusinessUnit x" )
} )
public class BusinessUnit implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="inactive__c")
    private Boolean    inactiveCustom ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Column(name="address_2__c", length=150)
    private String     address2Custom ;


    @Column(name="address_1__c", length=150)
    private String     address1Custom ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="market_area__c", length=18)
    private String     marketAreaCustom ;


    @Column(name="state__c", length=10)
    private String     stateCustom  ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Column(name="city__c", length=64)
    private String     cityCustom   ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Column(name="name", length=80)
    private String     name         ;


    @Column(name="bu_number__c", length=64)
    private String     buNumberCustom ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Column(name="country__c", length=10)
    private String     countryCustom ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;


    @Column(name="apply_same_rate_for_all_streams__c")
    private Boolean    applySameRateForAllStreamsCustom ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BusinessUnit()
    {
		super();
    }

    public BusinessUnit update(BusinessUnit a) {
		this.id = a.id;
        this.inactiveCustom = a.inactiveCustom;
        this.isdeleted = a.isdeleted;
        this.address2Custom = a.address2Custom;
        this.address1Custom = a.address1Custom;
        this.systemmodstamp = a.systemmodstamp;
        this.marketAreaCustom = a.marketAreaCustom;
        this.stateCustom = a.stateCustom;
        this.sfid = a.sfid;
        this.cityCustom = a.cityCustom;
        this.hcLastop = a.hcLastop;
        this.name = a.name;
        this.buNumberCustom = a.buNumberCustom;
        this.createddate = a.createddate;
        this.countryCustom = a.countryCustom;
        this.hcErr = a.hcErr;
        this.applySameRateForAllStreamsCustom = a.applySameRateForAllStreamsCustom;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : inactive__c ( bool ) 
    public void setInactiveCustom( Boolean inactiveCustom )
    {
        this.inactiveCustom = inactiveCustom;
    }
    public Boolean getInactiveCustom()
    {
        return this.inactiveCustom;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : address_2__c ( varchar ) 
    public void setAddress2Custom( String address2Custom )
    {
        this.address2Custom = address2Custom;
    }
    public String getAddress2Custom()
    {
        return this.address2Custom;
    }

    //--- DATABASE MAPPING : address_1__c ( varchar ) 
    public void setAddress1Custom( String address1Custom )
    {
        this.address1Custom = address1Custom;
    }
    public String getAddress1Custom()
    {
        return this.address1Custom;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : market_area__c ( varchar ) 
    public void setMarketAreaCustom( String marketAreaCustom )
    {
        this.marketAreaCustom = marketAreaCustom;
    }
    public String getMarketAreaCustom()
    {
        return this.marketAreaCustom;
    }

    //--- DATABASE MAPPING : state__c ( varchar ) 
    public void setStateCustom( String stateCustom )
    {
        this.stateCustom = stateCustom;
    }
    public String getStateCustom()
    {
        return this.stateCustom;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : city__c ( varchar ) 
    public void setCityCustom( String cityCustom )
    {
        this.cityCustom = cityCustom;
    }
    public String getCityCustom()
    {
        return this.cityCustom;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : bu_number__c ( varchar ) 
    public void setBuNumberCustom( String buNumberCustom )
    {
        this.buNumberCustom = buNumberCustom;
    }
    public String getBuNumberCustom()
    {
        return this.buNumberCustom;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : country__c ( varchar ) 
    public void setCountryCustom( String countryCustom )
    {
        this.countryCustom = countryCustom;
    }
    public String getCountryCustom()
    {
        return this.countryCustom;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : apply_same_rate_for_all_streams__c ( bool ) 
    public void setApplySameRateForAllStreamsCustom( Boolean applySameRateForAllStreamsCustom )
    {
        this.applySameRateForAllStreamsCustom = applySameRateForAllStreamsCustom;
    }
    public Boolean getApplySameRateForAllStreamsCustom()
    {
        return this.applySameRateForAllStreamsCustom;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(inactiveCustom);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(address2Custom);
        sb.append("|");
        sb.append(address1Custom);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(marketAreaCustom);
        sb.append("|");
        sb.append(stateCustom);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(cityCustom);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(buNumberCustom);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(countryCustom);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(applySameRateForAllStreamsCustom);
        return sb.toString(); 
    } 

}