/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wm.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "facility_contact_information__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="facility_contact_information__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="FacilityContactInformation.countAll", query="SELECT COUNT(x) FROM FacilityContactInformation x" )
} )
public class FacilityContactInformation implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="approval_status__c", length=255)
    private String     approvalStatusCustom ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Column(name="email__c", length=80)
    private String     emailCustom  ;


    @Column(name="phone__c", length=40)
    private String     phoneCustom  ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Column(name="recordtypeid", length=18)
    private String     recordtypeid ;


    @Column(name="name", length=80)
    private String     name         ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;


    @Column(name="operating_schedule__c", length=18)
    private String     operatingScheduleCustom ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public FacilityContactInformation()
    {
		super();
    }

    public FacilityContactInformation update(FacilityContactInformation a) {
		this.id = a.id;
        this.approvalStatusCustom = a.approvalStatusCustom;
        this.hcLastop = a.hcLastop;
        this.emailCustom = a.emailCustom;
        this.phoneCustom = a.phoneCustom;
        this.sfid = a.sfid;
        this.createddate = a.createddate;
        this.isdeleted = a.isdeleted;
        this.recordtypeid = a.recordtypeid;
        this.name = a.name;
        this.systemmodstamp = a.systemmodstamp;
        this.hcErr = a.hcErr;
        this.operatingScheduleCustom = a.operatingScheduleCustom;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : approval_status__c ( varchar ) 
    public void setApprovalStatusCustom( String approvalStatusCustom )
    {
        this.approvalStatusCustom = approvalStatusCustom;
    }
    public String getApprovalStatusCustom()
    {
        return this.approvalStatusCustom;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : email__c ( varchar ) 
    public void setEmailCustom( String emailCustom )
    {
        this.emailCustom = emailCustom;
    }
    public String getEmailCustom()
    {
        return this.emailCustom;
    }

    //--- DATABASE MAPPING : phone__c ( varchar ) 
    public void setPhoneCustom( String phoneCustom )
    {
        this.phoneCustom = phoneCustom;
    }
    public String getPhoneCustom()
    {
        return this.phoneCustom;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : recordtypeid ( varchar ) 
    public void setRecordtypeid( String recordtypeid )
    {
        this.recordtypeid = recordtypeid;
    }
    public String getRecordtypeid()
    {
        return this.recordtypeid;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : operating_schedule__c ( varchar ) 
    public void setOperatingScheduleCustom( String operatingScheduleCustom )
    {
        this.operatingScheduleCustom = operatingScheduleCustom;
    }
    public String getOperatingScheduleCustom()
    {
        return this.operatingScheduleCustom;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(approvalStatusCustom);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(emailCustom);
        sb.append("|");
        sb.append(phoneCustom);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(recordtypeid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(operatingScheduleCustom);
        return sb.toString(); 
    } 

}