/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wm.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "genesys_chat__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="genesys_chat__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="GenesysChat.countAll", query="SELECT COUNT(x) FROM GenesysChat x" )
} )
public class GenesysChat implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="state__c", length=10)
    private String     stateCustom  ;


    @Column(name="genesys_chat__c", length=255)
    private String     genesysChatCustom ;


    @Column(name="postal__c", length=50)
    private String     postalCustom ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Column(name="name", length=80)
    private String     name         ;


    @Column(name="genesys_ma__c", length=10)
    private String     genesysMaCustom ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public GenesysChat()
    {
		super();
    }

    public GenesysChat update(GenesysChat a) {
		this.id = a.id;
        this.isdeleted = a.isdeleted;
        this.systemmodstamp = a.systemmodstamp;
        this.stateCustom = a.stateCustom;
        this.genesysChatCustom = a.genesysChatCustom;
        this.postalCustom = a.postalCustom;
        this.hcLastop = a.hcLastop;
        this.name = a.name;
        this.genesysMaCustom = a.genesysMaCustom;
        this.createddate = a.createddate;
        this.sfid = a.sfid;
        this.hcErr = a.hcErr;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : state__c ( varchar ) 
    public void setStateCustom( String stateCustom )
    {
        this.stateCustom = stateCustom;
    }
    public String getStateCustom()
    {
        return this.stateCustom;
    }

    //--- DATABASE MAPPING : genesys_chat__c ( varchar ) 
    public void setGenesysChatCustom( String genesysChatCustom )
    {
        this.genesysChatCustom = genesysChatCustom;
    }
    public String getGenesysChatCustom()
    {
        return this.genesysChatCustom;
    }

    //--- DATABASE MAPPING : postal__c ( varchar ) 
    public void setPostalCustom( String postalCustom )
    {
        this.postalCustom = postalCustom;
    }
    public String getPostalCustom()
    {
        return this.postalCustom;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : genesys_ma__c ( varchar ) 
    public void setGenesysMaCustom( String genesysMaCustom )
    {
        this.genesysMaCustom = genesysMaCustom;
    }
    public String getGenesysMaCustom()
    {
        return this.genesysMaCustom;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(isdeleted);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(stateCustom);
        sb.append("|");
        sb.append(genesysChatCustom);
        sb.append("|");
        sb.append(postalCustom);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(genesysMaCustom);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(hcErr);
        return sb.toString(); 
    } 

}