/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wm.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "holiday_schedule__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="holiday_schedule__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="HolidaySchedule.countAll", query="SELECT COUNT(x) FROM HolidaySchedule x" )
} )
public class HolidaySchedule implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="hauling_hours_of_operation_close__c", length=255)
    private String     haulingHoursOfOperationCloseCustom ;


    @Column(name="other_delay_schedule__c", length=255)
    private String     otherDelayScheduleCustom ;


    @Column(name="recordtypeid", length=18)
    private String     recordtypeid ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Column(name="business_unit__c", length=18)
    private String     businessUnitCustom ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="market_area__c", length=18)
    private String     marketAreaCustom ;


    @Column(name="lob__c", length=255)
    private String     lobCustom    ;


    @Column(name="holiday__c", length=255)
    private String     holidayCustom ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;


    @Temporal(TemporalType.DATE)
    @Column(name="date__c")
    private Date       dateCustom   ;


    @Column(name="country__c", length=255)
    private String     countryCustom ;


    @Column(name="facility__c", length=18)
    private String     facilityCustom ;


    @Column(name="hauling_hours_of_operation_open__c", length=255)
    private String     haulingHoursOfOperationOpenCustom ;


    @Column(name="name", length=80)
    private String     name         ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Column(name="holiday_schedule__c", length=255)
    private String     holidayScheduleCustom ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public HolidaySchedule()
    {
		super();
    }

    public HolidaySchedule update(HolidaySchedule a) {
		this.id = a.id;
        this.haulingHoursOfOperationCloseCustom = a.haulingHoursOfOperationCloseCustom;
        this.otherDelayScheduleCustom = a.otherDelayScheduleCustom;
        this.recordtypeid = a.recordtypeid;
        this.isdeleted = a.isdeleted;
        this.businessUnitCustom = a.businessUnitCustom;
        this.sfid = a.sfid;
        this.systemmodstamp = a.systemmodstamp;
        this.marketAreaCustom = a.marketAreaCustom;
        this.lobCustom = a.lobCustom;
        this.holidayCustom = a.holidayCustom;
        this.hcErr = a.hcErr;
        this.dateCustom = a.dateCustom;
        this.countryCustom = a.countryCustom;
        this.facilityCustom = a.facilityCustom;
        this.haulingHoursOfOperationOpenCustom = a.haulingHoursOfOperationOpenCustom;
        this.name = a.name;
        this.hcLastop = a.hcLastop;
        this.holidayScheduleCustom = a.holidayScheduleCustom;
        this.createddate = a.createddate;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : hauling_hours_of_operation_close__c ( varchar ) 
    public void setHaulingHoursOfOperationCloseCustom( String haulingHoursOfOperationCloseCustom )
    {
        this.haulingHoursOfOperationCloseCustom = haulingHoursOfOperationCloseCustom;
    }
    public String getHaulingHoursOfOperationCloseCustom()
    {
        return this.haulingHoursOfOperationCloseCustom;
    }

    //--- DATABASE MAPPING : other_delay_schedule__c ( varchar ) 
    public void setOtherDelayScheduleCustom( String otherDelayScheduleCustom )
    {
        this.otherDelayScheduleCustom = otherDelayScheduleCustom;
    }
    public String getOtherDelayScheduleCustom()
    {
        return this.otherDelayScheduleCustom;
    }

    //--- DATABASE MAPPING : recordtypeid ( varchar ) 
    public void setRecordtypeid( String recordtypeid )
    {
        this.recordtypeid = recordtypeid;
    }
    public String getRecordtypeid()
    {
        return this.recordtypeid;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : business_unit__c ( varchar ) 
    public void setBusinessUnitCustom( String businessUnitCustom )
    {
        this.businessUnitCustom = businessUnitCustom;
    }
    public String getBusinessUnitCustom()
    {
        return this.businessUnitCustom;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : market_area__c ( varchar ) 
    public void setMarketAreaCustom( String marketAreaCustom )
    {
        this.marketAreaCustom = marketAreaCustom;
    }
    public String getMarketAreaCustom()
    {
        return this.marketAreaCustom;
    }

    //--- DATABASE MAPPING : lob__c ( varchar ) 
    public void setLobCustom( String lobCustom )
    {
        this.lobCustom = lobCustom;
    }
    public String getLobCustom()
    {
        return this.lobCustom;
    }

    //--- DATABASE MAPPING : holiday__c ( varchar ) 
    public void setHolidayCustom( String holidayCustom )
    {
        this.holidayCustom = holidayCustom;
    }
    public String getHolidayCustom()
    {
        return this.holidayCustom;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : date__c ( date ) 
    public void setDateCustom( Date dateCustom )
    {
        this.dateCustom = dateCustom;
    }
    public Date getDateCustom()
    {
        return this.dateCustom;
    }

    //--- DATABASE MAPPING : country__c ( varchar ) 
    public void setCountryCustom( String countryCustom )
    {
        this.countryCustom = countryCustom;
    }
    public String getCountryCustom()
    {
        return this.countryCustom;
    }

    //--- DATABASE MAPPING : facility__c ( varchar ) 
    public void setFacilityCustom( String facilityCustom )
    {
        this.facilityCustom = facilityCustom;
    }
    public String getFacilityCustom()
    {
        return this.facilityCustom;
    }

    //--- DATABASE MAPPING : hauling_hours_of_operation_open__c ( varchar ) 
    public void setHaulingHoursOfOperationOpenCustom( String haulingHoursOfOperationOpenCustom )
    {
        this.haulingHoursOfOperationOpenCustom = haulingHoursOfOperationOpenCustom;
    }
    public String getHaulingHoursOfOperationOpenCustom()
    {
        return this.haulingHoursOfOperationOpenCustom;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : holiday_schedule__c ( varchar ) 
    public void setHolidayScheduleCustom( String holidayScheduleCustom )
    {
        this.holidayScheduleCustom = holidayScheduleCustom;
    }
    public String getHolidayScheduleCustom()
    {
        return this.holidayScheduleCustom;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(haulingHoursOfOperationCloseCustom);
        sb.append("|");
        sb.append(otherDelayScheduleCustom);
        sb.append("|");
        sb.append(recordtypeid);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(businessUnitCustom);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(marketAreaCustom);
        sb.append("|");
        sb.append(lobCustom);
        sb.append("|");
        sb.append(holidayCustom);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(dateCustom);
        sb.append("|");
        sb.append(countryCustom);
        sb.append("|");
        sb.append(facilityCustom);
        sb.append("|");
        sb.append(haulingHoursOfOperationOpenCustom);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(holidayScheduleCustom);
        sb.append("|");
        sb.append(createddate);
        return sb.toString(); 
    } 

}