/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wm.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "market_area_table__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="market_area_table__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="MarketAreaTable.countAll", query="SELECT COUNT(x) FROM MarketAreaTable x" )
} )
public class MarketAreaTable implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="city__c", length=70)
    private String     cityCustom   ;


    @Column(name="name", length=80)
    private String     name         ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Column(name="state__c", length=15)
    private String     stateCustom  ;


    @Column(name="market_area_number__c", length=10)
    private String     marketAreaNumberCustom ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;


    @Column(name="country__c", length=50)
    private String     countryCustom ;


    @Column(name="address__c", length=255)
    private String     addressCustom ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MarketAreaTable()
    {
		super();
    }

    public MarketAreaTable update(MarketAreaTable a) {
		this.id = a.id;
        this.cityCustom = a.cityCustom;
        this.name = a.name;
        this.sfid = a.sfid;
        this.isdeleted = a.isdeleted;
        this.createddate = a.createddate;
        this.stateCustom = a.stateCustom;
        this.marketAreaNumberCustom = a.marketAreaNumberCustom;
        this.systemmodstamp = a.systemmodstamp;
        this.hcErr = a.hcErr;
        this.countryCustom = a.countryCustom;
        this.addressCustom = a.addressCustom;
        this.hcLastop = a.hcLastop;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : city__c ( varchar ) 
    public void setCityCustom( String cityCustom )
    {
        this.cityCustom = cityCustom;
    }
    public String getCityCustom()
    {
        return this.cityCustom;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : state__c ( varchar ) 
    public void setStateCustom( String stateCustom )
    {
        this.stateCustom = stateCustom;
    }
    public String getStateCustom()
    {
        return this.stateCustom;
    }

    //--- DATABASE MAPPING : market_area_number__c ( varchar ) 
    public void setMarketAreaNumberCustom( String marketAreaNumberCustom )
    {
        this.marketAreaNumberCustom = marketAreaNumberCustom;
    }
    public String getMarketAreaNumberCustom()
    {
        return this.marketAreaNumberCustom;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : country__c ( varchar ) 
    public void setCountryCustom( String countryCustom )
    {
        this.countryCustom = countryCustom;
    }
    public String getCountryCustom()
    {
        return this.countryCustom;
    }

    //--- DATABASE MAPPING : address__c ( varchar ) 
    public void setAddressCustom( String addressCustom )
    {
        this.addressCustom = addressCustom;
    }
    public String getAddressCustom()
    {
        return this.addressCustom;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(cityCustom);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(stateCustom);
        sb.append("|");
        sb.append(marketAreaNumberCustom);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(countryCustom);
        sb.append("|");
        sb.append(addressCustom);
        sb.append("|");
        sb.append(hcLastop);
        return sb.toString(); 
    } 

}