/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.wm.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "operating_schedule__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="operating_schedule__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="OperatingSchedule.countAll", query="SELECT COUNT(x) FROM OperatingSchedule x" )
} )
public class OperatingSchedule implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="name", length=80)
    private String     name         ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;


    @Column(name="monday_close__c", length=255)
    private String     mondayCloseCustom ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="sunday_close__c", length=255)
    private String     sundayCloseCustom ;


    @Column(name="saturday_close__c", length=255)
    private String     saturdayCloseCustom ;


    @Column(name="friday_open__c", length=255)
    private String     fridayOpenCustom ;


    @Column(name="wednesday_open__c", length=255)
    private String     wednesdayOpenCustom ;


    @Column(name="thursday_open__c", length=255)
    private String     thursdayOpenCustom ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastmodifieddate")
    private Date       lastmodifieddate ;


    @Column(name="tuesday_open__c", length=255)
    private String     tuesdayOpenCustom ;


    @Column(name="thursday_close__c", length=255)
    private String     thursdayCloseCustom ;


    @Column(name="time_zone__c", length=255)
    private String     timeZoneCustom ;


    @Column(name="lastmodifiedbyid", length=18)
    private String     lastmodifiedbyid ;


    @Column(name="other_schedule_information__c", length=255)
    private String     otherScheduleInformationCustom ;


    @Column(name="sunday_open__c", length=255)
    private String     sundayOpenCustom ;


    @Column(name="tuesday_close__c", length=255)
    private String     tuesdayCloseCustom ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Column(name="saturday_open__c", length=255)
    private String     saturdayOpenCustom ;


    @Column(name="monday_open__c", length=255)
    private String     mondayOpenCustom ;


    @Column(name="friday_close__c", length=255)
    private String     fridayCloseCustom ;


    @Column(name="wednesday_close__c", length=255)
    private String     wednesdayCloseCustom ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public OperatingSchedule()
    {
		super();
    }

    public OperatingSchedule update(OperatingSchedule a) {
		this.id = a.id;
        this.name = a.name;
        this.hcErr = a.hcErr;
        this.mondayCloseCustom = a.mondayCloseCustom;
        this.hcLastop = a.hcLastop;
        this.createddate = a.createddate;
        this.isdeleted = a.isdeleted;
        this.systemmodstamp = a.systemmodstamp;
        this.sundayCloseCustom = a.sundayCloseCustom;
        this.saturdayCloseCustom = a.saturdayCloseCustom;
        this.fridayOpenCustom = a.fridayOpenCustom;
        this.wednesdayOpenCustom = a.wednesdayOpenCustom;
        this.thursdayOpenCustom = a.thursdayOpenCustom;
        this.lastmodifieddate = a.lastmodifieddate;
        this.tuesdayOpenCustom = a.tuesdayOpenCustom;
        this.thursdayCloseCustom = a.thursdayCloseCustom;
        this.timeZoneCustom = a.timeZoneCustom;
        this.lastmodifiedbyid = a.lastmodifiedbyid;
        this.otherScheduleInformationCustom = a.otherScheduleInformationCustom;
        this.sundayOpenCustom = a.sundayOpenCustom;
        this.tuesdayCloseCustom = a.tuesdayCloseCustom;
        this.sfid = a.sfid;
        this.saturdayOpenCustom = a.saturdayOpenCustom;
        this.mondayOpenCustom = a.mondayOpenCustom;
        this.fridayCloseCustom = a.fridayCloseCustom;
        this.wednesdayCloseCustom = a.wednesdayCloseCustom;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id )
    {
        this.id = id ;
    }
    public Integer getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }

    //--- DATABASE MAPPING : monday_close__c ( varchar ) 
    public void setMondayCloseCustom( String mondayCloseCustom )
    {
        this.mondayCloseCustom = mondayCloseCustom;
    }
    public String getMondayCloseCustom()
    {
        return this.mondayCloseCustom;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : sunday_close__c ( varchar ) 
    public void setSundayCloseCustom( String sundayCloseCustom )
    {
        this.sundayCloseCustom = sundayCloseCustom;
    }
    public String getSundayCloseCustom()
    {
        return this.sundayCloseCustom;
    }

    //--- DATABASE MAPPING : saturday_close__c ( varchar ) 
    public void setSaturdayCloseCustom( String saturdayCloseCustom )
    {
        this.saturdayCloseCustom = saturdayCloseCustom;
    }
    public String getSaturdayCloseCustom()
    {
        return this.saturdayCloseCustom;
    }

    //--- DATABASE MAPPING : friday_open__c ( varchar ) 
    public void setFridayOpenCustom( String fridayOpenCustom )
    {
        this.fridayOpenCustom = fridayOpenCustom;
    }
    public String getFridayOpenCustom()
    {
        return this.fridayOpenCustom;
    }

    //--- DATABASE MAPPING : wednesday_open__c ( varchar ) 
    public void setWednesdayOpenCustom( String wednesdayOpenCustom )
    {
        this.wednesdayOpenCustom = wednesdayOpenCustom;
    }
    public String getWednesdayOpenCustom()
    {
        return this.wednesdayOpenCustom;
    }

    //--- DATABASE MAPPING : thursday_open__c ( varchar ) 
    public void setThursdayOpenCustom( String thursdayOpenCustom )
    {
        this.thursdayOpenCustom = thursdayOpenCustom;
    }
    public String getThursdayOpenCustom()
    {
        return this.thursdayOpenCustom;
    }

    //--- DATABASE MAPPING : lastmodifieddate ( timestamp ) 
    public void setLastmodifieddate( Date lastmodifieddate )
    {
        this.lastmodifieddate = lastmodifieddate;
    }
    public Date getLastmodifieddate()
    {
        return this.lastmodifieddate;
    }

    //--- DATABASE MAPPING : tuesday_open__c ( varchar ) 
    public void setTuesdayOpenCustom( String tuesdayOpenCustom )
    {
        this.tuesdayOpenCustom = tuesdayOpenCustom;
    }
    public String getTuesdayOpenCustom()
    {
        return this.tuesdayOpenCustom;
    }

    //--- DATABASE MAPPING : thursday_close__c ( varchar ) 
    public void setThursdayCloseCustom( String thursdayCloseCustom )
    {
        this.thursdayCloseCustom = thursdayCloseCustom;
    }
    public String getThursdayCloseCustom()
    {
        return this.thursdayCloseCustom;
    }

    //--- DATABASE MAPPING : time_zone__c ( varchar ) 
    public void setTimeZoneCustom( String timeZoneCustom )
    {
        this.timeZoneCustom = timeZoneCustom;
    }
    public String getTimeZoneCustom()
    {
        return this.timeZoneCustom;
    }

    //--- DATABASE MAPPING : lastmodifiedbyid ( varchar ) 
    public void setLastmodifiedbyid( String lastmodifiedbyid )
    {
        this.lastmodifiedbyid = lastmodifiedbyid;
    }
    public String getLastmodifiedbyid()
    {
        return this.lastmodifiedbyid;
    }

    //--- DATABASE MAPPING : other_schedule_information__c ( varchar ) 
    public void setOtherScheduleInformationCustom( String otherScheduleInformationCustom )
    {
        this.otherScheduleInformationCustom = otherScheduleInformationCustom;
    }
    public String getOtherScheduleInformationCustom()
    {
        return this.otherScheduleInformationCustom;
    }

    //--- DATABASE MAPPING : sunday_open__c ( varchar ) 
    public void setSundayOpenCustom( String sundayOpenCustom )
    {
        this.sundayOpenCustom = sundayOpenCustom;
    }
    public String getSundayOpenCustom()
    {
        return this.sundayOpenCustom;
    }

    //--- DATABASE MAPPING : tuesday_close__c ( varchar ) 
    public void setTuesdayCloseCustom( String tuesdayCloseCustom )
    {
        this.tuesdayCloseCustom = tuesdayCloseCustom;
    }
    public String getTuesdayCloseCustom()
    {
        return this.tuesdayCloseCustom;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : saturday_open__c ( varchar ) 
    public void setSaturdayOpenCustom( String saturdayOpenCustom )
    {
        this.saturdayOpenCustom = saturdayOpenCustom;
    }
    public String getSaturdayOpenCustom()
    {
        return this.saturdayOpenCustom;
    }

    //--- DATABASE MAPPING : monday_open__c ( varchar ) 
    public void setMondayOpenCustom( String mondayOpenCustom )
    {
        this.mondayOpenCustom = mondayOpenCustom;
    }
    public String getMondayOpenCustom()
    {
        return this.mondayOpenCustom;
    }

    //--- DATABASE MAPPING : friday_close__c ( varchar ) 
    public void setFridayCloseCustom( String fridayCloseCustom )
    {
        this.fridayCloseCustom = fridayCloseCustom;
    }
    public String getFridayCloseCustom()
    {
        return this.fridayCloseCustom;
    }

    //--- DATABASE MAPPING : wednesday_close__c ( varchar ) 
    public void setWednesdayCloseCustom( String wednesdayCloseCustom )
    {
        this.wednesdayCloseCustom = wednesdayCloseCustom;
    }
    public String getWednesdayCloseCustom()
    {
        return this.wednesdayCloseCustom;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(hcErr);
        sb.append("|");
        sb.append(mondayCloseCustom);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(sundayCloseCustom);
        sb.append("|");
        sb.append(saturdayCloseCustom);
        sb.append("|");
        sb.append(fridayOpenCustom);
        sb.append("|");
        sb.append(wednesdayOpenCustom);
        sb.append("|");
        sb.append(thursdayOpenCustom);
        sb.append("|");
        sb.append(lastmodifieddate);
        sb.append("|");
        sb.append(tuesdayOpenCustom);
        sb.append("|");
        sb.append(thursdayCloseCustom);
        sb.append("|");
        sb.append(timeZoneCustom);
        sb.append("|");
        sb.append(lastmodifiedbyid);
        sb.append("|");
        sb.append(otherScheduleInformationCustom);
        sb.append("|");
        sb.append(sundayOpenCustom);
        sb.append("|");
        sb.append(tuesdayCloseCustom);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(saturdayOpenCustom);
        sb.append("|");
        sb.append(mondayOpenCustom);
        sb.append("|");
        sb.append(fridayCloseCustom);
        sb.append("|");
        sb.append(wednesdayCloseCustom);
        return sb.toString(); 
    } 

}