/*
 * Created on 2017-09-12 ( Time 13:14:26 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.repository;

import com.wm.entities.AcceptableItems ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for AcceptableItems
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface AcceptableItemsRepository extends PagingAndSortingRepository<AcceptableItems, Integer> {
/*
		AcceptableItems findBySfid(String sfid);
*/

}