/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.repository;

import com.wm.entities.Facility ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for Facility
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface FacilityRepository extends PagingAndSortingRepository<Facility, Integer> {
/*
		Facility findBySfid(String sfid);
*/

}