/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.repository;

import com.wm.entities.FacilityContactInformation ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for FacilityContactInformation
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface FacilityContactInformationRepository extends PagingAndSortingRepository<FacilityContactInformation, Integer> {
/*
		FacilityContactInformation findBySfid(String sfid);
*/

}