/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.repository;

import com.wm.entities.HolidaySchedule ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for HolidaySchedule
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface HolidayScheduleRepository extends PagingAndSortingRepository<HolidaySchedule, Integer> {
/*
		HolidaySchedule findBySfid(String sfid);
*/

}