/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.repository;

import com.wm.entities.LclServiceAreaPostalCode ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for LclServiceAreaPostalCode
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface LclServiceAreaPostalCodeRepository extends PagingAndSortingRepository<LclServiceAreaPostalCode, Integer> {
/*
		LclServiceAreaPostalCode findBySfid(String sfid);
*/

}