/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.repository;

import com.wm.entities.Recordtype ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for Recordtype
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface RecordtypeRepository extends PagingAndSortingRepository<Recordtype, Integer> {
/*
		Recordtype findBySfid(String sfid);
*/

}