/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.services;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wm.entities.GenesysChat;
import com.wm.exceptions.GenesysChatNotFoundException;
import com.wm.repository.GenesysChatRepository;

@Service
@Transactional(rollbackFor=GenesysChatNotFoundException.class)
public class GenesysChatService 
{
	private static Logger logger = LoggerFactory.getLogger(GenesysChatService.class);
	
	@Autowired
	private GenesysChatRepository genesyschatRepository;
		
	/*
	 * READ methods
	 */
	public Page<GenesysChat> findAll(int page, int count) {
		
		if (logger.isDebugEnabled())
			logger.debug("GenesysChatService -> findAll GenesysChats");
		
		return genesyschatRepository.findAll(new PageRequest(page, count));
	}

	public Iterable<GenesysChat> findAll() {
		
		if (logger.isDebugEnabled())
			logger.debug("GenesysChatService -> findAll GenesysChats");
		
		return genesyschatRepository.findAll();
	}
/*
	public GenesysChat findBySfid(String genesyschat){
		if (logger.isDebugEnabled())
			logger.debug("Retrieving GenesysChat with sfid:" + genesyschat);
		
		return genesyschatRepository.findBySfid(genesyschat);
		
	}
*/
	public GenesysChat get(int id) {
		if (logger.isDebugEnabled())
			logger.debug("Retrieving GenesysChat with id:" + id);
		
		GenesysChat elementToGet = genesyschatRepository.findOne(id);
		
		if (elementToGet == null)
			throw new GenesysChatNotFoundException(id);
		
		return elementToGet;
	}

	public GenesysChat create(GenesysChat genesyschat) {

		if (logger.isDebugEnabled())
			logger.debug("GenesysChatService -> create:" + genesyschat);
			
		return genesyschatRepository.save(genesyschat);
	}

	public GenesysChat update(GenesysChat genesyschat) {
		
		if (logger.isDebugEnabled())
			logger.debug("GenesysChatService -> create:" + genesyschat);

		GenesysChat elementToUpdate = genesyschatRepository.findOne(genesyschat.getId());
		
		if (elementToUpdate == null)
			throw new GenesysChatNotFoundException(genesyschat.getName());
		
		elementToUpdate.update(genesyschat);
		genesyschatRepository.save(elementToUpdate);
		
		return elementToUpdate;
	}

	public GenesysChat delete(int id) {
		if (logger.isDebugEnabled())
			logger.debug("GenesysChatService -> delete:" + id);

		GenesysChat elementToDelete = get(id);
		
		if (elementToDelete == null)
			throw new GenesysChatNotFoundException(id);
		
		genesyschatRepository.delete(elementToDelete);

		return elementToDelete;
	}

}

