/*
 * Created on 2017-09-12 ( Time 13:14:27 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.wm.services;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wm.entities.MarketAreaTable;
import com.wm.exceptions.MarketAreaTableNotFoundException;
import com.wm.repository.MarketAreaTableRepository;

@Service
@Transactional(rollbackFor=MarketAreaTableNotFoundException.class)
public class MarketAreaTableService 
{
	private static Logger logger = LoggerFactory.getLogger(MarketAreaTableService.class);
	
	@Autowired
	private MarketAreaTableRepository marketareatableRepository;
		
	/*
	 * READ methods
	 */
	public Page<MarketAreaTable> findAll(int page, int count) {
		
		if (logger.isDebugEnabled())
			logger.debug("MarketAreaTableService -> findAll MarketAreaTables");
		
		return marketareatableRepository.findAll(new PageRequest(page, count));
	}

	public Iterable<MarketAreaTable> findAll() {
		
		if (logger.isDebugEnabled())
			logger.debug("MarketAreaTableService -> findAll MarketAreaTables");
		
		return marketareatableRepository.findAll();
	}
/*
	public MarketAreaTable findBySfid(String marketareatable){
		if (logger.isDebugEnabled())
			logger.debug("Retrieving MarketAreaTable with sfid:" + marketareatable);
		
		return marketareatableRepository.findBySfid(marketareatable);
		
	}
*/
	public MarketAreaTable get(int id) {
		if (logger.isDebugEnabled())
			logger.debug("Retrieving MarketAreaTable with id:" + id);
		
		MarketAreaTable elementToGet = marketareatableRepository.findOne(id);
		
		if (elementToGet == null)
			throw new MarketAreaTableNotFoundException(id);
		
		return elementToGet;
	}

	public MarketAreaTable create(MarketAreaTable marketareatable) {

		if (logger.isDebugEnabled())
			logger.debug("MarketAreaTableService -> create:" + marketareatable);
			
		return marketareatableRepository.save(marketareatable);
	}

	public MarketAreaTable update(MarketAreaTable marketareatable) {
		
		if (logger.isDebugEnabled())
			logger.debug("MarketAreaTableService -> create:" + marketareatable);

		MarketAreaTable elementToUpdate = marketareatableRepository.findOne(marketareatable.getId());
		
		if (elementToUpdate == null)
			throw new MarketAreaTableNotFoundException(marketareatable.getName());
		
		elementToUpdate.update(marketareatable);
		marketareatableRepository.save(elementToUpdate);
		
		return elementToUpdate;
	}

	public MarketAreaTable delete(int id) {
		if (logger.isDebugEnabled())
			logger.debug("MarketAreaTableService -> delete:" + id);

		MarketAreaTable elementToDelete = get(id);
		
		if (elementToDelete == null)
			throw new MarketAreaTableNotFoundException(id);
		
		marketareatableRepository.delete(elementToDelete);

		return elementToDelete;
	}

}

